BloggerBlogBundle_homepage:
    path:     /
    defaults: { _controller: "BloggerBlogBundle:Page:index" }
    requirements:
         methods:  GET

BloggerBlogBundle_about:
    path:   /about
    defaults: { _controller: "BloggerBlogBundle:Page:about" }
    requirements:
         methods:  GET

BloggerBlogBundle_contact:
    path:  /contact
    defaults: { _controller: "BloggerBlogBundle:Page:contact" }
    requirements:
        methods:  GET|POST
BloggerBlogBundle_content:
    path:  /show
    defaults: { _controller: "BloggerBlogBundle:Html:showContent" }
    requirements:
        methods:  GET|POST