BloggerBlogBundle_homepage:
    path:     /
    defaults: { _controller: "BloggerBlogBundle:Page:index" }
    requirements:
         methods:  GET

BloggerBlogBundle_about:
    path:   /about
    defaults: { _controller: "BloggerBlogBundle:Page:about" }
    requirements:
         methods:  GET

BloggerBlogBundle_contact:
    path:  /contact
    defaults: { _controller: "BloggerBlogBundle:Page:contact" }
    requirements:
        methods:  GET|POST
BloggerBlogBundle_content:
    path:  /show
    defaults: { _controller: "BloggerBlogBundle:Html:showContent" }
    requirements:
        methods:  GET|POST
BloggerBlogBundle_string:
    path: /string
    defaults: { _controller: "BloggerBlogBundle:String:index"}
    requirements:
        methods:  GET|POST
BloggerBlogBundle_stringin:
    path: /stringin
    defaults: { _controller: "BloggerBlogBundle:String:stringInString"}
    requirements:
        methods:  GET|POST
BloggerBlogBundle_lastindex:
    path: /lastindex
    defaults: { _controller: "BloggerBlogBundle:String:lastIndex"}
    requirements:
        methods:  GET|POST
BloggerBlogBundle_slices:
    path: /slices
    defaults: { _controller: "BloggerBlogBundle:String:slices"}
    requirements:
        methods:  GET|POST
BloggerBlogBundle_replace:
    path: /replace
    defaults: { _controller: "BloggerBlogBundle:String:replace"}
    requirements:
        methods:  GET|POST
BloggerBlogBundle_upper:
    path: /upper
    defaults: { _controller: "BloggerBlogBundle:String:upper"}
    requirements:
        methods:  GET|POST
BloggerBlogBundle_explode:
    path: /explode
    defaults: { _controller: "BloggerBlogBundle:String:explode"}
    requirements:
        methods:  GET|POST
BloggerBlogBundle_concat:
    path: /concat
    defaults: { _controller: "BloggerBlogBundle:String:concat"}
    requirements:
        methods:  GET|POST